### ISSUE TITLE
Add AI review summaries [Feature Request] 

### ISSUE THREAD

**Issue by IIpho3nix** [IIpho3nix/steam-extras#1]
## Add capabilities to summarise reviews with AI

**TODO:**
- [ ] Fetch the first 10 reviews using the provided URL.
- [ ] Format the reviews into an AI prompt.
- [ ] Utilize the Hugging Face interface API to generate summaries for the reviews.
- [ ] Display the generated summaries on the store page.

**Notes for self:**
- Use the following URL for fetching the reviews: `https://store.steampowered.com/appreviews/1237970?json=1&num_per_page=10`.
- Use the OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5 model for generating the summaries.

**Comment by IIpho3nix** [comment]
Feature cancelled as i cannot find a open source ai model that has enough context lenght to do it
